"""add initial institutions data

Revision ID: 8577f234078b
Revises: aa9333dcac08
Create Date: 2025-04-28 12:33:35.688221

"""
import datetime
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8577f234078b'
down_revision: Union[str, None] = 'aa9333dcac08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The data to be inserted into the institutions table
institutions_data = [
    {"name": "Texas Tech University", "city": "Lubbock, TX", "country": "USA"},
    {"name": "The George Washington University", "city": "Washington, D.C.", "country": "USA"},
    {"name": "West Virginia University", "city": "Morgantown, WV", "country": "USA"},
    {"name": "University of Cape Coast", "city": "Cape Coast", "country": "Ghana"},
    {"name": "University of Pretoria", "city": "Pretoria", "country": "South Africa"},
    {"name": "Kansas State University", "city": "Manhattan, KS", "country": "USA"},
    {"name": "University of Central Florida", "city": "Orlando, FL", "country": "USA"},
    {"name": "College of William and Mary", "city": "Williamsburg, VA", "country": "USA"},
    {"name": "George Mason University", "city": "Fairfax, VA", "country": "USA"},
    {"name": "New York University", "city": "New York, NY", "country": "USA"},
    {"name": "Clemson University", "city": "Clemson, SC", "country": "USA"},
    {"name": "Universidad de Panama", "city": "Panama City", "country": "Panama"},
    {"name": "California University of Pennsylvania", "city": "California, PA", "country": "USA"},
    {"name": "University of Malawi, Chancellor College", "city": "Zomba", "country": "Malawi"},
    {"name": "State University of New York at Geneseo", "city": "Geneseo, NY", "country": "USA"},
    {"name": "Sherubtse College, Royal University of Bhutan", "city": "Kanglung", "country": "Bhutan"},
    {"name": "Tribhuvan University - Pashchimanchal Campus", "city": "Pokhara", "country": "Nepal"},
    {"name": "State University of New York at Fredonia", "city": "Fredonia, NY", "country": "USA"},
    {"name": "Cornell University", "city": "Ithaca, NY", "country": "USA"},
    {"name": "Busitema University", "city": "Busitema", "country": "Uganda"},
    {"name": "Universidad de La Guajira", "city": "Riohacha", "country": "Colombia"},
    {"name": "Khulna University", "city": "Khulna", "country": "Bangladesh"},
    {"name": "University of Dhaka", "city": "Dhaka", "country": "Bangladesh"},
    {"name": "University of Nairobi", "city": "Nairobi", "country": "Kenya"},
    {"name": "Universidad Nacional de Colombia", "city": "Bogotá D.C.", "country": "Colombia"},
    {"name": "Universidad de los Andes", "city": "Bogotá D.C.", "country": "Colombia"},
    {"name": "Uganda Christian Univsersity", "city": "Mbale", "country": "Uganda"},
    {"name": "Universidad de Antioquia", "city": "Medellin", "country": "Colombia"},
    {"name": "Universidad de San Buenaventura - Medellin", "city": "Medellin", "country": "Colombia"},
    {"name": "Federal University of Technology, Akure", "city": "Akure", "country": "Nigeria"},
    {"name": "Makerere University", "city": "Kampala", "country": "Uganda"},
    {"name": "Dedan Kimathi University of Technology", "city": "NYERI", "country": "Kenya"},
    {"name": "University of Southern California", "city": "Los Angeles, CA", "country": "USA"},
    {"name": "Dhaka College", "city": "Dhaka City", "country": "Bangladesh"},
    {"name": "University of South Carolina", "city": "Columbia, SC", "country": "USA"},
    {"name": "Moi University", "city": "Eldoret", "country": "Kenya"},
    {"name": "Ahmadu Bello University Zaria", "city": "Zaria", "country": "Nigeria"},
    {"name": "Kumi University", "city": "Kumi District", "country": "Uganda"},
    {"name": "Gulu University", "city": "Gulu", "country": "Uganda"},
    {"name": "University of Oregon", "city": "Eugene, OR", "country": "USA"},
    {"name": "Asian University for Women", "city": "Chittagong", "country": "Bangladesh"},
    {"name": "Politecnico di Milano", "city": "Milan", "country": "Italy"},
    {"name": "Fourah Bay College, University of Sierra Leon", "city": "Freeetown", "country": "Sierra Leone"},
    {"name": "Universidad Distrital Francisco Jose de Caldas", "city": "Bogotá D.C.", "country": "Colombia"},
    {"name": "Far Eastern University - Institute of Technology", "city": "Manila City", "country": "Philippines"},
    {"name": "University of California, Davis", "city": "Davis, CA", "country": "USA"},
    {"name": "General Lansana Conte University", "city": "Conakry", "country": "Guinea"},
    {"name": "Gujarat University", "city": "Ahmedabad", "country": "India"},
    {"name": "Central Washington University", "city": "Ellensburg, WA", "country": "USA"},
    {"name": "University of Vermont", "city": "Burlington, VT", "country": "USA"},
    {"name": "Jomo Kenyatta University of Agriculture and Technology", "city": "Nairobi", "country": "Kenya"},
    {"name": "University of Liberia - Fendall Campus", "city": "Liberia", "country": "Louisiana"},
    {"name": "Stella Maris Polytechnic", "city": "Liberia", "country": "Monrovia"},
    {"name": "African Methodist Episcopal University", "city": "Monrovia", "country": "Liberia"},
    {"name": "Cuttington University", "city": "Liberia", "country": "Gbarnga"},
    {"name": "Institute of Science and Veterinary Medicine", "city": "Dalaba", "country": "Guinea"},
    {"name": "Université de N'Zérékoré", "city": "N'zérékoré", "country": "Guinea"},
    {"name": "University of Maryland - College Park", "city": "College Park, MD", "country": "USA"},
    {"name": "University of Ghana", "city": "Ghana", "country": "Legon"},
    {"name": "Centre Universitaire de Recherche et d'Application en Téléc", "city": "Côte d'Ivoire", "country": "Abidjan"},
    {"name": "University of Mines and Technology", "city": "Ghana", "country": "Tarkwa"},
    {"name": "The University of Zambia", "city": "Lusaka", "country": "Zambia"},
    {"name": "Insititue d' Enseignement Superieur de Ruhengeri", "city": "Rwanda", "country": "Musanze"},
    {"name": "Institution of Crisis Management Studies", "city": "Kathmandu", "country": "Nepal"},
    {"name": "University of Dar es Salaam", "city": "Tanzania, United Republic of", "country": "Dar es Salaam."},
    {"name": "Kigali institute of Science and Technology", "city": "Rwanda", "country": "Kigali"},
    {"name": "University of Port Harcourt", "city": "Port Harcourt", "country": "Nigeria"},
    {"name": "Sacred Heart Junior College", "city": "San Ignacio Town", "country": "Belize"},
    {"name": "Institute of Rural Development Planning", "city": "Tanzania, United Republic of", "country": "Mwanza"},
    {"name": "Kenyatta University", "city": "Nairobi", "country": "Kenya"},
    {"name": "Grand Gedeh County Community College", "city": "Liberia", "country": "Zwedru City"},
    {"name": "Institute of Rural Development Planning - Dodoma", "city": "Dodoma", "country": "Tanzania, United Republic of"},
    {"name": "The Citadel", "city": "Charleston, SC", "country": "USA"},
    {"name": "University of North Texas", "city": "USA", "country": "Denton, TX"},
    {"name": "University of Nigeria - Nsukka", "city": "Nsukka", "country": "Nigeria"},
    {"name": "Oklahoma State University", "city": "USA", "country": "Stillwater, OK"},
    {"name": "Heidelberg University, GIScience Research Group", "city": "Heidelberg", "country": "Germany"},
    {"name": "Federal School of Surveys", "city": "Oyo", "country": "Nigeria"},
    {"name": "University of Exeter", "city": "England", "country": "Exeter"},
    {"name": "University of Nigeria - Enugu", "city": "Enugu", "country": "Nigeria"},
    {"name": "University of Victoria", "city": "Victoria, BC", "country": "Canada"},
    {"name": "McGill University", "city": "Montreal, QC", "country": "Canada"},
    {"name": "Uganda Pentecostal University", "city": "Fortportal", "country": "Uganda"},
    {"name": "Ardhi University", "city": "Tanzania, United Republic of", "country": "Dar es Salaam"},
    {"name": "University of Warwick", "city": "England", "country": "Coventry"},
    {"name": "Mbarara University of Science and Technology", "city": "Uganda", "country": "Mbarara"},
    {"name": "Eastern University", "city": "Bangladesh", "country": "Dhaka"},
    {"name": "Universidad de Puerto Rico - Rio Piedras", "city": "Puerto Rico", "country": "San Juan"},
    {"name": "Jahangirnagar University", "city": "Dhaka", "country": "Bangladesh"},
    {"name": "Monroe Community College", "city": "Rochester", "country": "USA"},
    {"name": "Universidad de Costa Rica", "city": "San José", "country": "Costa Rica"},
    {"name": "Miami University", "city": "Oxford, OH", "country": "USA"},
    {"name": "Universidad Nacional Autónoma de Honduras", "city": "Tegucigalpa M.D.C.", "country": "Honduras"},
    {"name": "University of Wyoming", "city": "Laramie, WY", "country": "USA"},
    {"name": "University of Redlands", "city": "Redlands, CA", "country": "USA"},
    {"name": "Rajshahi University of Engineering & Technology", "city": "Rajshahi", "country": "Bangladesh"},
    {"name": "University of Twente", "city": "Enschede", "country": "Netherlands"},
    {"name": "Karatina University", "city": "Karatina", "country": "Kenya"},
    {"name": "Ignatius Ajuru University of Education", "city": "Port Harcourt", "country": "Nigeria"},
    {"name": "Université des Sciences Sociale et de Gestion de Bamako", "city": "Bamako", "country": "Mali"},
    {"name": "University of Northern Colorado", "city": "Greeley, CO", "country": "USA"},
    {"name": "Yarmouk University", "city": "Irbid", "country": "Jordan"},
    {"name": "Njala University, Njala Campus", "city": "Njala", "country": "Sierra Leone"},
    {"name": "Université Mohammed V Rabat", "city": "Rabat", "country": "Morocco"},
    {"name": "Université Gaston Berger", "city": "Saint Louis", "country": "Senegal"},
    {"name": "St. Augustine International University", "city": "Kampala", "country": "Uganda"},
    {"name": "University Muhammadiyah Surakarta", "city": "Surakarta", "country": "Indonesia"},
    {"name": "Queen Mary University of London", "city": "London", "country": "England"},
    {"name": "Villanova University", "city": "Villanova, PA", "country": "USA"},
    {"name": "UW-Madison", "city": "Madison, WI", "country": "USA"},
    {"name": "The Pennsylvania State University", "city": "University Park, PA", "country": "USA"},
    {"name": "University of the Gambia/Jokkolabs Banjul", "city": "Kanifing South", "country": "Gambia"},
    {"name": "Universitas Negeri Makassar", "city": "Makassar", "country": "Indonesia"},
    {"name": "Istanbul Technical University", "city": "Istanbul", "country": "Turkey"},
    {"name": "Universidade Eduardo Mondlane", "city": "Maputo City", "country": "Mozambique"},
    {"name": "Institut Supérieur de Management Kolda", "city": "Sare Mousa", "country": "Senegal"},
    {"name": "Kathmandu University", "city": "Kavre", "country": "Nepal"},
    {"name": "University of the Philippines Resilience Institute", "city": "Quezon City", "country": "Philippines"},
    {"name": "St. Mawaggali Trades Training Institute", "city": "Choma", "country": "Zambia"},
    {"name": "Kwame Nkrumah University of Science and Technology", "city": "Kumasi", "country": "Ghana"},
    {"name": "Nimba County Community College", "city": "Sanniquellie", "country": "Liberia"},
    {"name": "University of the West Indies, Mona Campus", "city": "Mona", "country": "Jamaica"},
    {"name": "University of Energy and Natural Resources", "city": "Sunyani", "country": "Ghana"},
    {"name": "Technical University of Kenya", "city": "Nairobi", "country": "Kenya"},
    {"name": "Abia State University", "city": "Uturu", "country": "Nigeria"},
    {"name": "Institute of Finance Management", "city": "Dar es salaam", "country": "Tanzania, United Republic of"},
    {"name": "Open University of Tanzania", "city": "Dar es salaam", "country": "Tanzania, United Republic of"},
    {"name": "Ball State University", "city": "Muncie, IN", "country": "USA"},
    {"name": "University of Chicago", "city": "Chicago, IL", "country": "USA"},
    {"name": "Vassar College", "city": "Poughkeepsie, NY", "country": "USA"},
    {"name": "Western Michigan University", "city": "Kalamazoo, MI", "country": "USA"},
    {"name": "Ohio Wesleyan University", "city": "Delaware, OH", "country": "USA"},
    {"name": "Njala University, Freetown Campus", "city": "Freetown", "country": "Sierra Leone"},
    {"name": "The Johns Hopkins University, SAIS", "city": "Washington, DC", "country": "USA"},
    {"name": "University of Zimbabwe", "city": "Harare", "country": "Zimbabwe"},
    {"name": "Indiana University of Pennsylvania", "city": "Indiana, PA", "country": "USA"},
    {"name": "Namibia University of Science and Technology", "city": "Windhoek", "country": "Namibia"},
    {"name": "Universidad Politecnica de Madrid", "city": "Madrid", "country": "Spain"},
    {"name": "Sokoine University of Agriculture", "city": "Morogoro", "country": "Tanzania, United Republic of"},
    {"name": "Jacksonville State University.", "city": "Jacksonville, AL", "country": "USA"},
    {"name": "Universidade de Santiago de Compostela", "city": "Santiago de Compos", "country": "Spain"},
    {"name": "Arizona State University", "city": "Tempe, AZ", "country": "USA"},
    {"name": "Institut Superieur des Mines et Géologie de Boké", "city": "Boké", "country": "Guinea"},
    {"name": "Serengeti Tourism College (SETCO)", "city": "Serengeti", "country": "Tanzania, United Republic of"},
    {"name": "National School of Forestry and Wildlife Management", "city": "Yaoundé", "country": "Cameroon"},
    {"name": "Shahjalal University of Science and Technology", "city": "Sylhet", "country": "Bangladesh"},
    {"name": "FEU Alabang", "city": "Muntinlupa City", "country": "Philippines"},
    {"name": "University of Douala", "city": "Douala", "country": "Cameroon"},
    {"name": "University of Education Winneba", "city": "Winneba", "country": "Ghana"},
    {"name": "American University", "city": "Washington, D.C.", "country": "USA"},
    {"name": "Comenius Polytechnic Institute", "city": "Tabora", "country": "Tanzania, United Republic of"},
    {"name": "Université Alassane Ouattara", "city": "Bouaké", "country": "Côte d'Ivoire"},
    {"name": "Lilongwe University of Agriculture and Natural Resources", "city": "Lilongwe", "country": "Malawi"},
    {"name": "Netrakona Govternment College", "city": "Netrakona", "country": "Bangladesh"},
    {"name": "Kyambogo University", "city": "Kampala", "country": "Uganda"},
    {"name": "Government Hazi Abdul Aziz Khan Degree College", "city": "Netrakona", "country": "Bangladesh"},
    {"name": "Purdue University", "city": "West Lafayette, IN", "country": "USA"},
    {"name": "Daffodil International University", "city": "Dhaka", "country": "Bangladesh"},
    {"name": "ASA University Bangladesh", "city": "Dhaka", "country": "Bangladesh"},
    {"name": "Addis Ababa Institute of Technology", "city": "Addis Ababa", "country": "Ethiopia"},
    {"name": "State University of Zanzibar", "city": "Zanzibar", "country": "Tanzania, United Republic of"},
    {"name": "State University of Bangladesh", "city": "Dhaka", "country": "Bangladesh"},
    {"name": "University of Lagos", "city": "Lagos", "country": "Nigeria"},
    {"name": "Mekelle University", "city": "Mekelle", "country": "Ethiopia"},
    {"name": "Université de Kisangani", "city": "Kisangani", "country": "Congo, The Democratic Republic of the"},
    {"name": "University of Dodoma", "city": "Dodoma", "country": "Tanzania, United Republic of"},
    {"name": "Okayama University of Science", "city": "Okayama", "country": "Japan"},
    {"name": "Keio University Shonan Fujisawa Campus", "city": "Fujisawa", "country": "Japan"},
    {"name": "The Nelson Mandela African Institution of Science and Technology (NM-AIST)", "city": "Arusha", "country": "Tanzania, United Republic of"},
    {"name": "University of Kinshasa", "city": "Kinshasa", "country": "Congo, The Democratic Republic of the"},
    {"name": "Maasai Mara University", "city": "Narok", "country": "Kenya"},
    {"name": "C.K. Tedam University of Technology and Applied Sciences", "city": "Navrongo", "country": "Ghana"},
    {"name": "Chinhoyi Univresity of Technology", "city": "Chinhoyi", "country": "Zimbabwe"},
    {"name": "Federal University of Parana (UFPR)", "city": "Curitiba", "country": "Brazil"},
    {"name": "Universitas Negeri Semarang", "city": "Semarang", "country": "Indonesia"},
    {"name": "SUMAIT UNIVERSITY", "city": "Zanzibar", "country": "Tanzania, United Republic of"},
    {"name": "Agriculture and Forestry University", "city": "Pokhara", "country": "Nepal"},
    {"name": "University of Benin", "city": "Benin city", "country": "Nigeria"},
    {"name": "Valley View University-Techiman", "city": "Techiman", "country": "Ghana"},
    {"name": "Aoyama Gakuin University", "city": "Sagamihara", "country": "Japan"},
    {"name": "Rowan University", "city": "Glassboro, NJ", "country": "USA"},
    {"name": "Institute of Survey and Land Management", "city": "Entebbe", "country": "Uganda"},
    {"name": "Murgwaza School of Nursing", "city": "Ngara", "country": "Tanzania, United Republic of"},
    {"name": "Ghana Schoolof Surveying and Mapping", "city": "Accra", "country": "Ghana"},
    {"name": "Masinde Muliro University of Science and Technology", "city": "Kakamega", "country": "Kenya"},
    {"name": "Egerton University", "city": "Njoro", "country": "Kenya"},
    {"name": "Universidad Nacional de San Antonio Abad del Cusco", "city": "Cusco", "country": "Perú"},
    {"name": "Muleba Lutheran Vocational Training Centre", "city": "Muleba", "country": "Tanzania, United Republic of"},
    {"name": "Kaduna Polytechnic", "city": "Kaduna", "country": "Nigeria"},
    {"name": "University of Gondar", "city": "Gondar", "country": "Ethiopia"},
    {"name": "Gombe State University", "city": "Gombe", "country": "Nigeria"},
    {"name": "National University, Manila", "city": "Manila", "country": "Philippines"},
    {"name": "Addis Ababa Science and Technology University", "city": "Addis Ababa", "country": "Ethiopia"},
    {"name": "Mai-Nefhi College of Science", "city": "Asmara", "country": "Eritrea"},
    {"name": "University of Utah", "city": "Salt Lake City", "country": "USA"},
    {"name": "University of Prešov", "city": "Prešov", "country": "Slovakia"},
    {"name": "Bangladesh University of Professionals", "city": "Dhaka Bangladesh", "country": "Bangladesh"},
    {"name": "Copperbelt University", "city": "KITWE", "country": "Zambia"},
    {"name": "Chittagong University Scientific Society (CUSS)", "city": "Chittagong", "country": "Bangladesh"},
    {"name": "University of Ibadan", "city": "Ibadan", "country": "Nigeria"},
    {"name": "University of Alaska", "city": "Anchorage, AK", "country": "USA"},
    {"name": "Dire Dawa University", "city": "Dire Dawa", "country": "Ethiopia"},
    {"name": "Adamawa State University", "city": "Mubi", "country": "Nigeria"},
    {"name": "Kaduna State University", "city": "Kaduna", "country": "Nigeria"},
    {"name": "Ashesi University", "city": "Berekuso", "country": "Ghana"},
    {"name": "Federal University of Technology - Minna", "city": "Minna", "country": "Nigeria"},
    {"name": "University of Jos", "city": "Jos", "country": "Nigeria"},
    {"name": "University of Makeni", "city": "Makeni", "country": "Sierra Leone"},
    {"name": "Debre Birhan University", "city": "Debre Birhan", "country": "Ethiopia"},
    {"name": "Universidade Federal da Bahia", "city": "Salvador da Bahia", "country": "Brazil"},
    {"name": "North South University", "city": "Dhaka", "country": "Bangladesh"},
    {"name": "World University of Bangladesh", "city": "Dhaka", "country": "Bangladesh"},
    {"name": "Tribhuvan University - Lamjung Campus, Institute of Agricu", "city": "Sundarbazar", "country": "Nepal"},
    {"name": "Northern Technical College", "city": "Ndola", "country": "Zambia"},
    {"name": "Evelyn Hone college", "city": "Lusaka", "country": "Zambia"},
    {"name": "Tribhuvan University - Paklihawa Campus, Institute of Agric", "city": "Bhairahawa", "country": "Nepal"},
    {"name": "Natural Resources Development College", "city": "Lusaka", "country": "Zambia"},
    {"name": "Kwame Nkrumah University Zambia", "city": "Kabwe", "country": "Zambia"},
    {"name": "University of Maiduguri", "city": "Maiduguri", "country": "Nigeria"},
    {"name": "University of Business and Intergrated Development Studie", "city": "Washington", "country": "Ghana"},
    {"name": "Central University - Sierra Leone", "city": "Tonkolili", "country": "Sierra Leone"},
    {"name": "Universidad Autónoma del Estado de México", "city": "Toluca", "country": "Mexico"},
    {"name": "University of Colorado Boulder", "city": "Boulder, CO", "country": "USA"},
    {"name": "Université de Ségou", "city": "Ségou", "country": "Mali"},
    {"name": "Universidad de las Fuerzas Armadas-ESPE", "city": "Sangolqui", "country": "Ecuador"},
    {"name": "Instituto de Educación Superior Privado Khipu", "city": "Cusco", "country": "Peru"},
    {"name": "Universidade Federal de Mato Grosso do Sul, Campus de A/", "city": "Aquidauana", "country": "Brazil"},
    {"name": "Old Dominion University", "city": "Norfolk, VA", "country": "USA"},
    {"name": "Universidade Federal de São João del Rei", "city": "São João del Rei", "country": "Brazil"},
    {"name": "Bangabandhu Sheikh Mujibur Rahman Science & Technolog", "city": "Gopalganj", "country": "Bangladesh"},
    {"name": "Universidade Federal da Paraíba", "city": "João Pessoa", "country": "Brazil"},
    {"name": "Tishk International University", "city": "Erbil", "country": "Iraq"},
    {"name": "Bangabandhu Sheikh Mujibur Rahman Maritime University", "city": "Dhaka City", "country": "Bangladesh"},
    {"name": "Université Catholique de Bukavu", "city": "Bukavu", "country": "Congo, The Democratic Republic of the"},
    {"name": "University of Duhok", "city": "Duhok", "country": "Iraq"},
    {"name": "Instituto Federal de Educação, Ciência e Tecnologia do Para", "city": "Castanhal", "country": "Brazil"},
    {"name": "Catholic University of Rwanda", "city": "Butare", "country": "Rwanda"},
    {"name": "Jashore University of Science & Technology", "city": "Jashore", "country": "Bangladesh"},
    {"name": "Universite du Sine Saloum Elhadj Ibrahima Niass (USSEIN)", "city": "Kaolack", "country": "Senegal"},
    {"name": "Somali National University", "city": "Mogadisho", "country": "Somalia"},
    {"name": "Instituto Superior de Ciencias de Educação da Huila", "city": "Lubango", "country": "Angola"},
    {"name": "Kigali Independent University", "city": "Kigali", "country": "Rwanda"},
    {"name": "Universidade Federal Rural da Amazônia (UFRA)", "city": "Belém", "country": "Brazil"},
    {"name": "University of Makati", "city": "Metro Manila", "country": "Philippines"},
    {"name": "The Federal Polytechnic Ede, Osun State", "city": "Ede", "country": "Nigeria"},
    {"name": "Laikipia University", "city": "NYAHURURU", "country": "Kenya"},
    {"name": "Institut Supérieur de Technologie d'Ambositra", "city": "Ambositra", "country": "Madagascar"},
    {"name": "Universidade do Estado da Bahia", "city": "Serrinha, BA", "country": "Brazil"},
    {"name": "Maseno University", "city": "Kisumu", "country": "Kenya"},
    {"name": "Doon University", "city": "Dehradun", "country": "India"},
    {"name": "Malawi University of Science and Technology", "city": "Thyolo", "country": "Malawi"},
    {"name": "East Africa University", "city": "Qardho", "country": "Somalia"},
    {"name": "Universida de Manizales", "city": "Manizales", "country": "Colombia"},
    {"name": "University of the Philippines Visayas Tacloban College", "city": "Tacloban", "country": "Philippines"},
    {"name": "Nanyang Technological University Singapore", "city": "Singapore", "country": "Singapore"},
    {"name": "Chreso University", "city": "Lusaka", "country": "Zambia"},
    {"name": "Federal University Lokoja Kogi State", "city": "Lokoja", "country": "Nigeria"},
    {"name": "Université Julius Nyerere de Kankan (UJNK)", "city": "Kankan", "country": "Guinea"},
    {"name": "University of Northern lowa", "city": "Cedar Falls, IA", "country": "USA"},
    {"name": "University of Bari Aldo Moro", "city": "Bari", "country": "Italy"},
    {"name": "Universite de Kara", "city": "Kara", "country": "Togo"},
    {"name": "Erbil Polytechnic University", "city": "Erbil", "country": "Iraq"},
    {"name": "Federal University of Kashere", "city": "Kashere", "country": "Nigeria"},
    {"name": "Politecnico di Bari", "city": "Bari", "country": "Italy"},
    {"name": "Umaru Musa Yar'adua University Katsina (UMYUK)", "city": "Katsina State", "country": "Nigeria"},
    {"name": "University of Eswatini, Kwaluseni Campus", "city": "Matsapha", "country": "Eswatini"},
    {"name": "Universidad Nacional de Asunción", "city": "San Lorenzo", "country": "Paraguay"},
    {"name": "Universidad Autónoma Metropolitana Unidad Cuajimalpa", "city": "Ciudad de México", "country": "México"},
    {"name": "Sulu State College", "city": "Jolo", "country": "Philippines"},
    {"name": "Wollega University", "city": "Nekemte", "country": "Ethiopia"},
    {"name": "Institute of Accountancy Arusha", "city": "Arusha", "country": "Tanzania, United Republic of"},
    {"name": "Universidade Federal do Acre", "city": "Rio Branco", "country": "Brazil"},
    {"name": "University of Nouakchott Al Aasriya", "city": "Nouakchott", "country": "Mauritania"},
    {"name": "Frostburg State University", "city": "Frostburg", "country": "United States of America"},
    {"name": "Kabale University", "city": "Kabale", "country": "Uganda"},
    {"name": "University of Science and Technology of Southern Philippin", "city": "Cagayan de Oro", "country": "Philippines"},
    {"name": "Eastern Technical University of Sierra Leone", "city": "Kenema", "country": "Sierra Leone"},
    {"name": "Eastern University", "city": "Vantharumoolai", "country": "Sri Lanka"},
    {"name": "Dilla University", "city": "Dilla", "country": "Ethiopia"},
    {"name": "American International Universiy West Africa", "city": "Brusubi", "country": "Gambia"},
    {"name": "Bahir Dar University", "city": "Bahir Dar", "country": "Ethiopia"},
    {"name": "Muni University", "city": "Arua", "country": "Uganda"},
    {"name": "Bicol University", "city": "Legazpi City", "country": "Philippines"},
    {"name": "Malawi University of Business and Applied Sciences", "city": "Blantyre", "country": "Malawi"},
    {"name": "Texas A&M University", "city": "College Station, TX", "country": "United States of America"},
    {"name": "Wolkite University", "city": "Wolkite", "country": "Ethiopia"},
    {"name": "Universidade Federal de Goiás", "city": "Goiânia", "country": "Brazil"},
    {"name": "University of Khartoum", "city": "Khartoum", "country": "Sudan"},
    {"name": "University of British Columbia", "city": "Vancouver", "country": "Canada"},
    {"name": "Catholic University of Mozambique", "city": "Pemba", "country": "Mozambique"},
    {"name": "Université Denis Sassou Nguesso", "city": "Kintélé", "country": "Republic of the Congo"},
    {"name": "Université Officielle de Bukavu", "city": "Bukavu", "country": "Congo, The Democratic Republic of the"},
    {"name": "University of Burundi", "city": "Bujumbura", "country": "Burundi"},
    {"name": "University of Ilorin", "city": "Ilorin", "country": "Nigeria"},
    {"name": "University of Tripoli", "city": "Tripoli", "country": "Libya"},
    {"name": "Universite Kongo", "city": "Mbanza-ngungu", "country": "Congo, The Democratic Republic of the"},
    {"name": "Universidad Galileo", "city": "Guatemala", "country": "Guatemala"},
    {"name": "Universidad de San Carlos de Guatemala - Centro Universitario de Occidente", "city": "Quetzaltenango", "country": "Guatemala"},
    {"name": "Kenya Institute of Surveying and Mapping", "city": "Nairobi", "country": "Kenya"},
    {"name": "Yaba College of Technology", "city": "Yaba", "country": "Nigeria"},
    {"name": "United Methodist University", "city": "Monrovia", "country": "Liberia"},
    {"name": "University of Rajshahi", "city": "Rajshahi City", "country": "Bangladesh"},
    {"name": "Hacettepe University", "city": "Ankara", "country": "Turkey"},
    {"name": "Obafemi Awolowo University, Ile-Ife", "city": "Ile-Ife", "country": "Nigeria"},
    {"name": "Jatiya Kabi Kazi Nazrul Islam University", "city": "Mymensingh", "country": "Bangladesh"},
    {"name": "Visayas State University", "city": "Baybay City", "country": "Philippines"},
    {"name": "Midlands State University", "city": "Gweru", "country": "Zimbabwe"},
    {"name": "Texas Christian University", "city": "Fort Worth, TX", "country": "United States of America"},
    {"name": "Patuakhali Science & Technology University", "city": "Patuakhali", "country": "Bangladesh"},
    {"name": "Indian Institute of Technology (BHU), Varanasi", "city": "Varanasi", "country": "India"},
    {"name": "Dar es salaam University College of Education", "city": "Dar es Salaam", "country": "Tanzania, United Republic of"},
    {"name": "Universidad Centroamericana José Simeón Cañas", "city": "Antiguo Cuscatlán", "country": "El Salvador"},
    {"name": "Ho Technical University", "city": "Ho", "country": "Ghana"},
    {"name": "Jordan University College", "city": "Morogoro", "country": "Tanzania, United Republic of"},
    {"name": "Universidad Mayor de San Andrés", "city": "La Paz", "country": "Bolivia"},
    {"name": "Universidade Estadual do Rio Grande do Sul", "city": "Porto Alegre", "country": "Brazil"},
    {"name": "Universidade Federal da Viçosa", "city": "Rio Paranaíba", "country": "Brazil"},
    {"name": "Hawassa University", "city": "Hawassa", "country": "Ethiopia"},
    {"name": "Mzuzu University", "city": "Mzuzu", "country": "Malawi"},
    {"name": "Towson University", "city": "Towson", "country": "United States of America"},
    {"name": "Universidade Federal de Uberlandia", "city": "Uberlandia", "country": "Brazil"},
    {"name": "Technical University Munich", "city": "Munich", "country": "Germany"},
    {"name": "Institut Catholique de Kabgayi", "city": "Muhanga", "country": "Rwanda"},
    {"name": "Sunyani Technical University", "city": "Sunyani", "country": "Ghana"},
    {"name": "Tamale College of Education", "city": "Sagnarigu", "country": "Ghana"},
    {"name": "University of Arkansas", "city": "Fayetteville", "country": "United States of America"},
    {"name": "Instituto Superior Politecnico de Songo", "city": "Tete", "country": "Mozambique"},
    {"name": "Universidad Nacional de Colombia, Sede Medellin", "city": "Medellin", "country": "Colombia"},
    {"name": "Eastern Visayas State University - Main Campus", "city": "Tacloban City", "country": "Philippines"},
    {"name": "Polytechnic University Timisoara", "city": "Timisoara", "country": "Romania"},
    {"name": "University of the Witwatersrand, Johannesburg", "city": "Johannesburg", "country": "South Africa"},
    {"name": "Samara University of Ethiopia", "city": "Samara", "country": "Ethiopia"},
    {"name": "Southern Leyte State University", "city": "Sogod", "country": "Philippines"},
    {"name": "Nkhoma University", "city": "Lilongwe", "country": "Malawi"},
    {"name": "Universidad Nacional Mayor de San Marcos", "city": "Lima", "country": "Peru"},
    {"name": "Bahirdar University", "city": "Bahirdar", "country": "Ethiopia"},
    {"name": "University of Barishal", "city": "Barishal", "country": "Bangladesh"},
    {"name": "College of Business Education", "city": "Dar es salaam", "country": "Tanzania, United Republic of"},
    {"name": "Mzumbe University", "city": "Morogoro", "country": "Tanzania, United Republic of"},
    {"name": "Bells University Of Technology", "city": "Ota", "country": "Nigeria"},
    {"name": "Palestine Ahliya University (PAU)", "city": "Bethlahem", "country": "Palestine"},
    {"name": "Princess Sumaya University for Technology", "city": "Al-Jubeiha", "country": "Jordan"},
    {"name": "University of Sri Jayewardenepura", "city": "Sri Jayewardenepura", "country": "Sri Lanka"},
    {"name": "Lagos State University", "city": "Ojo", "country": "Nigeria"},
    {"name": "South Eastern University of Sri Lanka", "city": "Oluvil", "country": "Sri Lanka"},
    {"name": "Gwanda State University", "city": "Filabusi", "country": "Zimbabwe"},
    {"name": "Catholic University of Malawi", "city": "Chiradzulu", "country": "Malawi"},
    {"name": "Sabaragamuwa University of Sri Lanka", "city": "Pambahinna", "country": "Sri Lanka"},
    {"name": "Texas State University", "city": "San Marcos", "country": "United States of America"},
    {"name": "University of Toronto", "city": "Toronto", "country": "Canada"},
    {"name": "Lira University", "city": "Lira", "country": "Uganda"},
    {"name": "Del Mar College", "city": "Corpus Christi", "country": "United States of America"},
    {"name": "Universidade Federal do Piauí", "city": "Teresina", "country": "Brazil"},
    {"name": "Eberswalde University for Sustainable Development", "city": "Eberwalde", "country": "Germany"},
    {"name": "Jaramogi Oginga Odinga University of science and technolo", "city": "Bondo", "country": "Kenya"},
    {"name": "University of Illinois at Urbana Champaign", "city": "Chamapign", "country": "United States of America"},
    {"name": "University of Limpopo", "city": "Makweng", "country": "South Africa"},
    {"name": "Universidade Federal do Rio de Janeiro", "city": "Rio de Janeiro", "country": "Brazil"},
    {"name": "University of Mines and Technology - School of Railways an", "city": "Essikado", "country": "Ghana"},
    {"name": "Oregon State University", "city": "Corvallis", "country": "United States of America"},
    {"name": "Universitas Pendidikan Indonesia", "city": "Bandung City", "country": "Indonesia"},
    {"name": "Federal Rural University of Rio de Janeiro", "city": "Seropédica", "country": "Brazil"},
    {"name": "Universidade Federal do ABC", "city": "São Bernardo do Car", "country": "Brazil"},
    {"name": "Leyte Normal University", "city": "Tacloban City", "country": "Philippines"},
    {"name": "Universidad de El Salvador - Facultad Multidisciplinaria de", "city": "Santa Ana", "country": "El Salvador"},
    {"name": "Tuskegee University", "city": "Tuskegee", "country": "United States of America"},
    {"name": "Universidad Regional Amazónica IKIAM", "city": "Tena", "country": "Ecuador"},
    {"name": "Kampala International University in Tanzania", "city": "Dar Es Salaam", "country": "Uganda"},
    {"name": "Government Shahid Suhrawardy College", "city": "Dhaka", "country": "Bangladesh"},
    {"name": "Universidade do Estado do Rio de Janeiro", "city": "Rio de Janeiro", "country": "Brazil"},
    {"name": "Adamson University", "city": "Manila", "country": "Philippines"},
    {"name": "Adama Science and Technology University", "city": "Adama", "country": "Ethiopia"},
    {"name": "Western Mindanao State University", "city": "Zamboanga City", "country": "Philippines"},
    {"name": "Mt. San Antonio College", "city": "Walnut, CA", "country": "United States of America"},
    {"name": "University of Bohol", "city": "Tagbilaran City", "country": "Philippines"},
    {"name": "Escola Superior de Agricultura Luiz de Queiroz - Universidad", "city": "Piracicaba", "country": "Brazil"},
    {"name": "Ndejje University", "city": "Luwero", "country": "Uganda"},
    {"name": "Federal University of Agriculture", "city": "Abeokuta", "country": "Nigeria"},
    {"name": "University of Cincinnati", "city": "Cincinnati", "country": "USA"},
    {"name": "University of the Philippines Mindanao", "city": "Davao City", "country": "Philippines"},
    {"name": "Middle East Technical University Northern Cyprus Campus", "city": "Kalkanlı", "country": "Cyprus"},
    {"name": "The Ohio State University", "city": "Columbus", "country": "United States of America"},
    {"name": "Northwest Samar State University", "city": "Calbayog City", "country": "Philippines"},
    {"name": "Jalal-Abad State University", "city": "Jalal-Abad", "country": "Kyrgyzstan"},
    {"name": "Universidade Federal Fluminense", "city": "Niterói", "country": "Brazil"},
    {"name": "Zanzibar University", "city": "Zanzibar", "country": "Tanzania"},
    {"name": "Universidad Autónoma Metropolitana, Unidad Iztapalapa", "city": "Iztapalapa", "country": "Mexico"},
    {"name": "University of MissouriSt -Louis", "city": "St Louis, MO", "country": "USA"},
    {"name": "University College London", "city": "London", "country": "England"},
    {"name": "Federation University Australia", "city": "Ballarat", "country": "Australia"},
    {"name": "Sir Arthur Lewis Community College", "city": "Castries", "country": "St. Lucia"},
    {"name": "Instituto Federal de Minas Gerais", "city": "Betim", "country": "Brazil"},
    {"name": "Universidad Juárez del Estado de Durango", "city": "Durango", "country": "Mexico"},
    {"name": "University of Fianarantsoa", "city": "Fianarantsoa", "country": "Madagascar"},
    {"name": "National University of Science and Technology", "city": "Bulawayo", "country": "Zimbabwe"},
    {"name": "Reitaku University", "city": "Minami Kashiwa", "country": "Japan"},
    {"name": "Savannakhet University", "city": "Savannakhet", "country": "Laos"},
    {"name": "Universidad Externado de Colombia", "city": "Bogota", "country": "Colombia"},
    {"name": "Universidade Federal Do Pampa, Campus Alegrete", "city": "Alegrete", "country": "Brazil"},
    {"name": "Rangamati Science and Technology University", "city": "Rangamati", "country": "Bangladesh"},
    {"name": "Universidad Nacional de San Agustín de Arequipa", "city": "Arequipa", "country": "Peru"},
    {"name": "Nueva Ecija University of Science and Technology", "city": "Cabanatuan City", "country": "Philippines"},
    {"name": "Universidade Federal Fluminense", "city": "Goytacazes", "country": "Brazil"},
    {"name": "Universidade Federal Do Oeste da Bahia", "city": "Barra", "country": "Brazil"},
    {"name": "University of Hargeisa", "city": "Hargiesa", "country": "Somalia"},
    {"name": "Universidad Catolica de Santa María", "city": "Arequipa", "country": "Peru"},
    {"name": "Universidad Nacional de Trujillo", "city": "Trujillo", "country": "Peru"},
    {"name": "The University of the West IndiesSt.", "city": "Augustine", "country": "Trinidad & Tobago"},
    {"name": "Instituto Federal de Educação, Ciência e Tecnologia do Pará", "city": "Belém", "country": "Brazil"},
    {"name": "University of Southeastern Philippines", "city": "Davao City", "country": "Philippines"},
    {"name": "Far Western University", "city": "Mahendranagar", "country": "Nepal"},
    {"name": "Caraga State University - Main Campus", "city": "Butuan City", "country": "Philippines"},
    {"name": "Qatar University", "city": "Doha", "country": "Qatar"},
    {"name": "Srinakharinwirot University", "city": "Bangkok", "country": "Thailand"},
    {"name": "Universidad Jorge Tadeo Lozano", "city": "Bogotá", "country": "Colombia"},
    {"name": "SIMAD University", "city": "Mogadishu", "country": "Somalia"},
    {"name": "Universidad Privada Antenor Orrego", "city": "Trujillo", "country": "Peru"},
    {"name": "Universidad del Valle", "city": "Cali", "country": "Colombia"},
    {"name": "Universitas Negeri Jakarta", "city": "East Jakarta", "country": "Indonesia"},
    {"name": "Pabna University of Science and Technology", "city": "Pabna", "country": "Bangladesh"},
    {"name": "Garissa University", "city": "Garissa", "country": "Kenya"},
    {"name": "Technical University of Moldova", "city": "Chișinău", "country": "Moldova"},
    {"name": "Siliguri Government Polytechnic", "city": "Siliguri", "country": "India"},
    {"name": "Universidad Nacional de Ingenieria", "city": "Managua", "country": "Nicaragua"},
    {"name": "Montgomery College", "city": "Rockville, MD", "country": "USA"},
    {"name": "Universidad Autónoma de Madrid", "city": "Madrid", "country": "Spain"},
]


def upgrade() -> None:
    """
    Inserts initial data into the institutions table.
    """
    # Define the table structure as it exists in the database
    institutions_table = sa.table(
        "institutions",
        sa.column("id", sa.String),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
        sa.column("name", sa.String),
        sa.column("city", sa.String),
        sa.column("country", sa.String),
        sa.column("OSM_mapping", sa.Integer),
        sa.column('is_updated', sa.Boolean)  # Assuming this is a boolean column
        # Add other columns if they exist in your table, e.g., column("id", sa.Integer)
    )

    # Prepare data with generated UUIDs and the is_updated flag
    data_to_insert = []
    for data in institutions_data:
        data_to_insert.append({
            'id': str(uuid.uuid4()), # Generate a UUID for each row
            'created_at': datetime.datetime.utcnow(), # Set created_at to current time
            'updated_at': datetime.datetime.utcnow(), # Set updated_at to current time
            'name': data['name'],
            'city': data['city'],
            'country': data['country'],
            'is_updated': False,  # Set is_updated to False for initial entries
            'OSM_mapping': 0 # Set is_updated to False for initial entries
        })

    # Use bulk_insert_mappings for efficient insertion
    op.bulk_insert(institutions_table, data_to_insert)


def downgrade() -> None:
    """
    Removes the initial data from the institutions table.
    """
    # Define the table structure
    institutions_table = sa.table(
        "institutions",
        sa.column("name", sa.String),
        sa.column("city", sa.String)
        # You might only need the 'name' column to filter for deletion
    )

    # Delete the inserted data.
    # A simple approach for initial data is to delete all rows.
    # If your table might contain other data, you would need a more specific filter.
    # op.execute(institutions_table.delete())

    # Alternatively, to delete only the specific rows inserted:
    # You would need to construct a filter based on the data. This is more complex
    # and often unnecessary for initial seed data unless there's a risk of
    # deleting other data unintentionally.
    for inst_data in institutions_data:
        op.execute(
            institutions_table.delete().where(
                institutions_table.c.name == inst_data["name"],
                institutions_table.c.city == inst_data["city"],
                # Add other conditions if needed for uniqueness
            )
        )