"""created all tables

Revision ID: aa9333dcac08
Revises: 
Create Date: 2025-04-28 12:25:18.248756

"""
from datetime import datetime
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa9333dcac08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False, default=lambda: str(uuid.uuid4())),
    sa.Column('created_at', sa.DateTime(), nullable=False, default=datetime.utcnow()),
    sa.Column('updated_at', sa.DateTime(), nullable=False, default=datetime.utcnow()),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('chapter_name', sa.String(length=128), nullable=True),
    sa.Column('OSM_mapping', sa.Integer(), nullable=False, default=0),
    sa.Column('contributor_full_name', sa.String(length=128), nullable=True),
    sa.Column('contributor_email', sa.String(length=128), nullable=True),
    sa.Column('contributor_phone_number', sa.String(length=30), nullable=True),
    sa.Column('role_in_chapter', sa.String(length=128), nullable=True),
    sa.Column('is_updated', sa.Boolean(), nullable=False, default=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contributor_email'),
    sa.UniqueConstraint('contributor_phone_number')
    )
    op.create_table('geofiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('imagefiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagefiles')
    op.drop_table('geofiles')
    op.drop_table('institutions')
    # ### end Alembic commands ###
