"""added attr (delete) to reltionship in models

Revision ID: e4bcfc820e34
Revises: 9e03e47a8127
Create Date: 2025-04-21 16:45:16.880157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bcfc820e34'
down_revision: Union[str, None] = '9e03e47a8127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
